### ISSUE TITLE
Unify `AsyncExceptionWrapper` and friends between `safe-exceptions` and `unliftio`

### ISSUE THREAD

**Issue by parsonsmatt** [fpco/unliftio#102]
The `UnliftIO.Exception` module contains a large copy/paste of code and types from `safe-exceptions`, including items like `AsyncExceptionWrapper`, `SyncExceptionWrapper`, etc.

Program behavior may change if you switch from `Control.Exception.Safe.throwTo` to `UnliftIO.Exception.throwTo` - if you do a `catch` and expect an `Control.Exception.Safe.AsyncExceptionWrapper`, then you'll fail to catch the wrapped type.

Since the types are the same, it seems to make sense to unify them.

This could mean depending on `safe-exceptions` directly, or factoring the type out into a separate package.

If we *do* depend on `safe-exceptions` directly, then we can also unify `Handler` #101, since `exceptions` is a dependency of `safe-exceptions`.

**Comment by snoyberg** [comment]
This makes sense. Overall my preference is moving away from safe-exceptions, but that's unlikely to take complete hold. I'd be OK with adding the dependency here for both this issue and #101.

**Comment by snoyberg** [comment]
No strong feeling honestly. If we need the dependency on `exceptions` regardless, having `safe-exceptions-io` doesn't seem to add much besides one more dependency in the chain.
