### ISSUE TITLE
How mature is this library nowadays?

### ISSUE THREAD

**Issue by Qqwy** [fpco/unliftio#121]
The README still starts with the following note at the top:

> NOTE This library is young, and will likely undergo some serious changes over time. It's also very lightly tested. 

At the same time, it now is already 7+ years old, and seems to have been adopted quite widely in the Haskell ecosystem.
Is this note still accurate, or should it be reworded or removed?

**Comment by snoyberg** [comment]
It's definitely inaccurate, this is one of the most stable libraries I maintain :). PR welcome to update the text, thank you for noticing.
