### ISSUE TITLE
MonadUnliftIO and streaming

### ISSUE THREAD

**Issue by gbwey** [fpco/unliftio#17]
I've converted some of my code over to using  MonadUnliftIO, but I still have a lot of code that uses the Streaming package. 

[https://hackage.haskell.org/package/streaming-0.1.4.5/docs/Streaming-Internal.html]

Here's the ADT for it: 

data Stream f m r = Step !(f (Stream f m r))
                  | Effect (m (Stream f m r))
                  | Return r

This uses MonadBase, MonadResource, MonadCatch etc, but is there any way to get this to work to support MonadUnliftIO instead?

Thanks for any help!
Grant

**Comment by snoyberg** [comment]
Continuation-based monads cannot have instances of `MonadUnliftIO`, the same as `MonadBaseControl` and `MonadMask`. This is the primary motivation of having `MonadResource` in the first place: the ability to safely acquire resources inside a continuation-based monad.

**Comment by gbwey** [comment]
Thanks for letting me know
