### ISSUE TITLE
Bug: docs should be louder about changed async exception semantics

### ISSUE THREAD

**Issue by ntc2** [fpco/unliftio#23]
The mostly great overview documentation for the `unliftio` library waits until page 7 to mention that the library changes the semantics of async exceptions. Since the main unlifting concept is easy to understand from the examples, and is orthogonal to changing async exception semantics, I expect many people don't read all the way to the end and never imagine the library would also change async semantics. Some of those people (me) will then spend hours debugging subtle problems related to the changed async exception semantics. I propose that the documentation make it loud and clear, from the beginning, that the library changes async exception semantics and is not simply a drop in generalization of `Control.Exception` when it comes to exceptions.

The "Quickstart" on the first page of the docs does say "Replace imports like Control.Exception with UnliftIO.Exception. Yay, your catch and finally are more powerful and safer!", with "safer" here hinting at the changed semantics, but I don't think that's going to help anyone who doesn't already know that `unliftio` takes the `safe-exceptions` approach. In fact, the docs even give an example of implementing an `unliftio` version of `mask`, which is one of the exception-related functions that does not change async semantics, encouraging further confusion.

Because the unlifting is orthogonal to the safe exceptions, I suppose the best approach would be to make the safe exceptions opt-in, by making two versions of the library, say `unliftio-traditional-exceptions` and `unliftio-safe-exceptions`; might be a nice use for backpack when it's mature.

**Comment by snoyberg** [comment]
I have no intention of providing two versions of the library, I would
consider it a bug to promote async-unsafe code now that we know better ways
to do it. If you'd like to send a PR to improve the documentation, I'd be
happy to review.

**Comment by ntc2** [comment]
Sounds good, see PR #24.

**Comment by ntc2** [comment]
In case you're wondering what I was doing with async exceptions that broke when I started using `unliftio`, it's related to this: https://github.com/simonmar/async/issues/25.
