### ISSUE TITLE
Unnamed third law in class definition should be called "Invertibility"

### ISSUE THREAD

**Issue by justinpastoncooper** [fpco/unliftio#26]
Isn't the law equivalent to "lifting must be invertible"?

**Comment by snoyberg** [comment]
I don't see the connection between the third law and invertibility, sorry.

**Comment by justinpastoncooper** [comment]
Isn't the third law really the essence of `UnliftIO`? `MonadLiftIO` takes `m a` into `IO a`, and `MonadUnliftIO` takes it back. In that sense, isn't this equivalent to invertibility?

**Comment by snoyberg** [comment]
Yes, sort of, but it's missing the essential distinguishing fact of the law: that the monad context is the same, and there are no missing monad state updates.

**Comment by justinpastoncooper** [comment]
Isn't "monad context is the same" implied by invertibility? Maybe I don't fully understand.

**Comment by snoyberg** [comment]
Addressed in #41
