### ISSUE TITLE
Is it possible to define a pass-through instance if the transformer constructor is not in scope?

### ISSUE THREAD

**Issue by mbwgh** [fpco/unliftio#31]
I've been trying to define a `MonadUnliftIO` instance for haskeline's `InputT`, i.e. something like

```haskell
instance MonadUnliftIO m => MonadUnliftIO (InputT m) where,
```
or rather for a newtype wrapper around it. Of course, I wouldn't be asking if I had succeeded.
Should I expect this to be possible if I do not have access to the internals of `InputT` ?

In this special case, there might be work-arounds via either the low-level IO module, or via haskeline's `MonadException` stuff, but of course this doesn't generalize.

**Comment by snoyberg** [comment]
It's probably not possible in general, unless there are sufficient helper functions available to work with `InputT` already.

**Comment by mbwgh** [comment]
Thanks for the reply. I figured as much after trying to implement a few more instances, and unless you have access to the monadic context, i.e. the `ReaderT` constructor, you are forced to drop it entirely.

A follow-up: I have spent more time than I am comfortable to admit trying to figure out how to implement a `MonadUnliftIO` instance for a newtype, such that it delegates to the underlying type, without reimplementing the logic of the `ReaderT r m` instance for example.

In the end I implemented a helper function

```haskell
liftedRunInIO :: MonadUnliftIO n => (n b -> m b) -> (forall a. m a -> n a) -> ((forall a. m a -> IO a) -> IO b) -> m b
liftedRunInIO up down inner = up $ withRunInIO $ \run ->
  inner $ run . down
```

and used it in a few places like this:

```haskell
newtype AppT m a = AppT { unAppT :: ReaderT TheStuff (ResourceT m) a }
  deriving (Functor, Applicative, Monad, MonadIO, MonadReader TheStuff)

instance MonadUnliftIO m => MonadUnliftIO (AppT m) where
  withRunInIO = liftedRunInIO AppT unAppT
```

Do you think a helper in this spirit (suitably generalized, constrained, or corrected in case it is wrong) would be useful? While it is just a trivial combinator in hindsight, I found neither of the two typeclass methods terribly intuitive when starting out.

**Comment by mbwgh** [comment]
Closing, since the question itself has been answered.
