### ISSUE TITLE
Include Companion?

### ISSUE THREAD

**Issue by snoyberg** [fpco/unliftio#42]
I wrote an implementation of what I've called "companion threads" for Stack:

https://github.com/commercialhaskell/stack/blob/42b4ce73653174f777015b4099c8021b35136590/subs/pantry/src/Pantry/Internal/Companion.hs

It's theoretically a general-purpose concept, and would fit in well with this library: it introduces no additional dependencies, and nicely generalizes to `MonadUnliftIO`. However, I'm not sure if the idea is fully fleshed out yet and warrants being included here. Feedback welcome.

**Comment by lehins** [comment]
I am certainly in favor of having "companions" in `unliftio`

**Comment by snoyberg** [comment]
@nh2 gave some pushback on this in an offline conversation, since this can be addressed with `race` (or similar) instead. My motivation was to bypass async exceptions for a common case, but it's probably not worth adding a new abstraction for this. Closing.
