### ISSUE TITLE
Why is forkWithUnmask not called forkIOWithUnmask?

### ISSUE THREAD

**Issue by peti** [fpco/unliftio#44]
`UnliftIO.Concurrent` provides a function called `forkWithUnmask`, which is an unlifted variant of `forkIOWithUnmask`. Now, all other unlifted functions provided by the library match the name of their original -- but this does one does not. Was that choice intentional?

**Comment by snoyberg** [comment]
It may have been intentional, I don't remember, but I agree with your analysis: `forkIOWithUnmask` would be a better name. You interested in sending a PR to add that function, optionally deprecating the current name?

**Comment by peti** [comment]
For what it's worth, I'd like to say thank you for the effort you've put into this library. I find it very useful and I am using it happily in my own code.

**Comment by snoyberg** [comment]
That's great to hear :)
