### ISSUE TITLE
The RIO monad.

### ISSUE THREAD

**Issue by nickkuk** [fpco/unliftio#6]
Let me keep discussion around [the `RIO` monad](https://www.fpcomplete.com/blog/2017/07/the-rio-monad) aproach.

I've already used monad `RIO` a lot in my commercial GUI application that is based on [`sdl2`](https://github.com/haskell-game/sdl2) and [`reactive-banana`](https://github.com/HeinrichApfelmus/reactive-banana) libraries and targets to Windows-Linux desktops and ARM embedded; it must be fast, responsive and robust as it works 24/7 on [this sensor stand](http://www.ceramic3d.ru/cat/TouchStand/stands.jpg).

At now I use the following module:
```haskell
{-# LANGUAGE GeneralizedNewtypeDeriving #-}

module UnliftIO.MonadRIO where

import Control.Monad.IO.Class (MonadIO, liftIO)
import Control.Monad.Reader (MonadReader, ReaderT (ReaderT))
import Control.Monad.Trans.Resource (MonadResource, liftResourceT, MonadThrow, ResourceT,
                                     InternalState, runInternalState, withInternalState)
import Control.Monad.Base (MonadBase)
import Control.Lens (Lens', view)
import UnliftIO (MonadUnliftIO)

newtype RIO env a = RIO { unRIO :: ReaderT env IO a }
  deriving (Functor, Applicative, Monad, MonadIO, MonadReader env,
            MonadThrow, MonadBase IO, MonadUnliftIO)

{-# INLINE runRIO #-}
runRIO :: MonadIO m => env -> RIO env a -> m a
runRIO env (RIO (ReaderT f)) = liftIO (f env)

instance HasResources env => MonadResource (RIO env) where
  {-# INLINE liftResourceT #-}
  liftResourceT resT = view resourcesL >>= liftIO . runResources resT

newtype Resources = Resources InternalState

{-# INLINE runResources #-}
runResources :: ResourceT m a -> Resources -> m a
runResources action (Resources intState) = runInternalState action intState

{-# INLINE withResources #-}
withResources :: (Resources -> m a) -> ResourceT m a
withResources action = withInternalState (action . Resources)

class HasResources env where
  resourcesL :: Lens' env Resources

instance HasResources Resources where
  {-# INLINE resourcesL #-}
  resourcesL = id
```

[`UnliftIO.Exception`](https://www.stackage.org/haddock/lts-9.9/unliftio-0.1.0.0/UnliftIO-Exception.html) gives me capabilities of [`safe-exceptions`](https://www.stackage.org/package/safe-exceptions) and [`lifted-base`](https://www.stackage.org/package/lifted-base), [`UnliftIO.Async`](https://www.stackage.org/haddock/lts-9.9/unliftio-0.1.0.0/UnliftIO-Async.html) gives safe lifted [`async`](https://www.stackage.org/package/async); also I've added #5 to get almost full (and in the same time safer) strength of [`lifted-base`](https://www.stackage.org/package/lifted-base).

In this issue I want to discuss
1. the possibility to add the `RIO` monad to `unliftio-core` or `unliftio` or anywhere else;
2. interaction of the `RIO` monad with `ResourceT` - at now I use `lens` and ```instance HasResources env => MonadResource (RIO env)```;
3. interaction with [`monad-logger`](https://www.stackage.org/package/monad-logger).

**Comment by snoyberg** [comment]
I'm in favor of adding a `RIO` which is `unliftio` aware. For dependency reasons, that may make sense in a separate package from `unliftio` itself (perhaps a `rio` package, for example). Stack already defines such a data type internally, and I'm in favor of putting it somewhere more generic. I'm also happy with including it in this megarepo, even if it doesn't end up inside `unliftio` or `unliftio-core`.

For interaction with `ResourceT`: I _would_ go with the kind of approach you've taken here, though I'm not sure if I'd use a proper `Lens`, versus a simple function. There are advantages to both approaches, and the `RIO` ecosystem should choose one and stick with it. I'm leaning towards simple functions, as the lens approach doesn't gain us very much, and adds both complexity and slightly more brittle APIs (harder to make changes without breaking backwards compatibility).

**Comment by FongHou** [comment]
Sorry to post this here. I'm a beginner who just have an idea but don't know how to appoarch it. Basically, I'd like to be able to use MonadManaged with RIO. It seems I need to implement two things:

instance MonadManaged (RIO env) where
   using resource = ...

and an unlifted version of with :: Managed a -> (a -> IO r) -> IO r

with ::  (MonadUnliftIO m) => Managed a -> (a -> m r) -> m r

I've tried to write them by studying code here and other MonadManaged instances, but completely lost in continuation passing/capturing logic. Any advice and suggestions will be greatly appreciated!

**Comment by snoyberg** [comment]
I assume you're referring to https://www.stackage.org/haddock/lts-10.0/managed-1.0.5/Control-Monad-Managed.html#t:MonadManaged.

I'm not familiar with `MonadManaged`, but from what I can see: it's impossible. Notice that the class in question does not have an instance for `IO`.

**Comment by FongHou** [comment]
Thanks for the response.

It has an instance for https://hackage.haskell.org/package/turtle-1.5.0/docs/src/Turtle-Shell.html#line-194. I thought it may be possible as Shell type has a shape of (FoldShell a r-> IO r), which is very similar to (env -> IO r) as RIO.

**Comment by snoyberg** [comment]
Pretty sure it's not possible. The `Shell` type looks like it's following a continuation-passing style, whereas `RIO` is not. The idea is that, in `Shell`, the actions to be performed are in the `FoldShell a r` value itself, and therefore you can wrap things up in appropriate cleanup functions.

I think you'll want to stick with the `with` function.

**Comment by FongHou** [comment]
I understand it now. Thank you for the explanation!
