### ISSUE TITLE
flushTBQueue and lengthTBQueue are missing

### ISSUE THREAD

**Issue by sharno** [fpco/unliftio#61]
`flushTBQueue` is missing:
https://hackage.haskell.org/package/stm-2.5.0.0/docs/Control-Concurrent-STM-TBQueue.html#v:flushTBQueue

Also `lengthTBQueue`:
https://hackage.haskell.org/package/stm-2.5.0.0/docs/Control-Concurrent-STM-TBQueue.html#v:lengthTBQueue

**Comment by snoyberg** [comment]
PR welcome
