### ISSUE TITLE
Why no QSem and QSemN?

### ISSUE THREAD

**Issue by Smart-Hypercube** [fpco/unliftio#69]
Hi, I use rio (and thus unliftio) a lot, and would like to get unlifted versions of Control.Concurrent.QSem and Control.Concurrent.QSemN from RIO. I know that sometimes rio does not re-export a module or a function because it has problems (like Control.Exception), and I would like to know such reasons. Is there any problem with QSem modules?

I often find scenarios where I need to easily limit concurrent jobs. For example, I spawn a child process for each request, and wait for it to finish before sending back the response. I would like to limit the number of processes running in order to avoid OOMs. I think QSem is best suited for this kind of logics. I know I can use Chan, but it requires spawning threads as workers and it's difficult to send back the response. I can also use Pool, but it seems unnecessary because the child processes are not reusable resources -- they always get destroyed after finish.

**Comment by snoyberg** [comment]
No reason in particular, just an oversight. PR welcome for adding it!

**Comment by Smart-Hypercube** [comment]
I'll close this now. Thank you for your help and timely responses!
