### ISSUE TITLE
Allow unliftio-core-0.1.2.0 with base-4.14

### ISSUE THREAD

**Issue by lrworth** [fpco/unliftio#71]
[`amazonka-1.6.1`](http://hackage.haskell.org/package/amazonka-1.6.1) (the latest release) depends on `unliftio-core (==0.1.*)`, [the latest version of which](http://hackage.haskell.org/package/unliftio-core-0.1.2.0) will not build with GHC 8.10 due to the dependency on `base (>=4.5 && <4.14)`. I've got unliftio-core to build just fine with GHC 8.10 by manually allowing `base >=4.5 && <4.15`. I propose making a revision on the package in Hackage to allow this so that people can use amazonka with GHC 8.10.

What do you think?

**Comment by snoyberg** [comment]
Generally I don't like revisions or maintaining older versions of packages. But I know that amazonka is difficult to patch these days. Revision added. Thanks for the ping.

**Comment by lrworth** [comment]
That is super helpful! Thank you!
