### ISSUE TITLE
Add helper function for converting exceptions?

### ISSUE THREAD

**Issue by brandon-leapyear** [fpco/unliftio#73]
`Control.Exception` has a `mapException` function that can convert exceptions in impure contexts, but not for exceptions thrown in a monadic context:
```hs
{-# LANGUAGE DeriveAnyClass #-}
data Exception1 = Exception1 deriving (Show, Exception)
data Exception2 = Exception2 deriving (Show, Exception)
mapException (\Exception1 -> Exception2) (throwIO Exception1)
```
returns `Exception1`. It would be great if `unliftio` could provide a helper that would convert exceptions in a monadic context, maybe something like
```hs
mapExceptionIO :: (MonadUnliftIO m, Exception e1, Exception e2) => (e1 -> e2) -> m a -> m a
mapExceptionIO f = handle (throwIO . f)
```

**Comment by snoyberg** [comment]
Seems reasonable to me, I'd accept such a PR.
