### ISSUE TITLE
add createFileLink 

### ISSUE THREAD

**Issue by yaitskov** [fpco/unliftio#77]
I guess unliftio goal is to rexexport System.Directory functions with lifted IO monad.
I noticed that createFileLink is not provided.
Is it exported from other place? IMHO the function name doesn't fit well into the origin namespace, does it?

**Comment by yaitskov** [comment]
just in case https://github.com/fpco/unliftio/pull/78

**Comment by Gabriel439** [comment]
Also, `createDirectoryLink` is missing, too

**Comment by Gabriel439** [comment]
Also, `removeDirectoryLink`
