### ISSUE TITLE
Eq instance for StringException?

### ISSUE THREAD

**Issue by brandon-leapyear** [fpco/unliftio#82]
Would it make sense to add an `Eq` instance for `StringException`? I'm writing tests for functions that should handle arbitrary errors, and it would be nice to just do
```hs
let e = stringException "asdf"
res <- tryAny $ withFoo (\_ -> throwIO e)
res `shouldBe` Left e
```
Right now, I'm forced to write my own exception type and use that.

**Comment by snoyberg** [comment]
Overall it seems fine. One concern: we may in theory want to add backtrace support to this type, and an `Eq` instance wouldn't work there. But in practice I don't see a strong reason to hold off on the feature. PR welcome :)
