### ISSUE TITLE
Functor instance for Handler

### ISSUE THREAD

**Issue by anpryl** [fpco/unliftio#89]
`Handler` from `safe-exceptions` has `Functor` instance:
https://hackage.haskell.org/package/safe-exceptions-0.1.7.2/docs/Control-Exception-Safe.html#t:Handler

Is it possible to add `Functor` to `unliftio`s `Handler`?

**Comment by snoyberg** [comment]
I don't see a problem with that, PR welcome.

**Comment by LiamGoodacre** [comment]
Looks like the safe-exceptions `Handler` is re-exported now (since https://github.com/fpco/unliftio/commit/9c1f2750d8bc69f33b47ac9716e49b2b5dfca222), so this can prolly be closed

**Comment by snoyberg** [comment]
Cool, thanks!
